# Generated by Django 4.2.3 on 2023-07-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='lore',
        ),
        migrations.AddField(
            model_name='event',
            name='age',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='event',
            name='imagine',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='img',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.IntegerField(),
        ),
    ]
