# Generated by Django 4.2.3 on 2023-07-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_img_alter_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TextField(),
        ),
    ]
