# Generated by Django 4.2.3 on 2023-07-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_alter_character_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='species',
            field=models.CharField(max_length=250),
        ),
    ]
