# Generated by Django 4.2.3 on 2023-07-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_alter_character_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='location',
            field=models.CharField(default='', max_length=250),
        ),
    ]
