# Generated by Django 4.2.3 on 2023-07-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('blurb', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('discovered', models.BooleanField()),
                ('species', models.TextField()),
                ('geodynamics', models.TextField()),
                ('magictechnology', models.TextField()),
                ('img', models.CharField(max_length=250)),
            ],
        ),
    ]
