# Generated by Django 4.2.3 on 2023-07-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='imagine',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='world',
            name='img',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='world',
            name='lore',
            field=models.JSONField(default=list),
        ),
    ]
