# Generated by Django 4.2.3 on 2023-07-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0002_rename_geodymanics_world_geodynamics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='geodynamics',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='world',
            name='magictechnology',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='world',
            name='species',
            field=models.JSONField(),
        ),
    ]
