# Generated by Django 4.2.3 on 2023-07-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0003_alter_world_geodynamics_alter_world_magictechnology_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='magictechnology',
            field=models.TextField(),
        ),
    ]
