# Generated by Django 4.2.3 on 2023-07-09 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0008_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='world',
            new_name='world_id',
        ),
    ]
