# Generated by Django 4.2.3 on 2023-07-09 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0009_rename_world_location_world_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('race', models.CharField(max_length=250)),
                ('alignment', models.CharField(max_length=250)),
                ('attributes', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('img', models.CharField(max_length=250)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds.location')),
                ('world_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds.world')),
            ],
        ),
    ]
