# Generated by Django 4.2.3 on 2023-07-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0011_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.CharField(default='none', max_length=250),
        ),
        migrations.AddField(
            model_name='world',
            name='characters',
            field=models.JSONField(default='none'),
        ),
        migrations.AddField(
            model_name='world',
            name='history',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='world',
            name='locations',
            field=models.JSONField(default='none'),
        ),
        migrations.AlterField(
            model_name='world',
            name='img',
            field=models.TextField(default='none'),
        ),
    ]
