# Generated by Django 4.2.3 on 2023-07-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0012_event_time_location_type_world_characters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='events',
            field=models.JSONField(default='none'),
        ),
    ]
