# Generated by Django 4.2.3 on 2023-07-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0013_world_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='characters',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='world',
            name='events',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='world',
            name='history',
            field=models.TextField(default=dict),
        ),
        migrations.AlterField(
            model_name='world',
            name='locations',
            field=models.JSONField(default=dict),
        ),
    ]
