# Generated by Django 4.2.3 on 2023-07-13 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0014_alter_world_characters_alter_world_events_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='world',
            name='characters',
        ),
        migrations.RemoveField(
            model_name='world',
            name='events',
        ),
        migrations.RemoveField(
            model_name='world',
            name='locations',
        ),
    ]
