# Generated by Django 4.2.3 on 2023-07-13 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0015_remove_world_characters_remove_world_events_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='world',
            old_name='magictechnology',
            new_name='magicTechnology',
        ),
    ]
