# Generated by Django 4.2.3 on 2023-07-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0016_rename_magictechnology_world_magictechnology'),
    ]

    operations = [
        migrations.RenameField(
            model_name='world',
            old_name='geodynamics',
            new_name='geoDynamics',
        ),
        migrations.AlterField(
            model_name='world',
            name='discovered',
            field=models.BooleanField(default=False),
        ),
    ]
