AESTHETICS = {
"earthly": [
"1950s Suburbia",
"Abstract Tech",
"Afrofuturism",
"American Pioneers",
"American Revolution",
"Americana",
"Ancient Egypt",
"Art Deco",
"Art Nouveau",
"Atompunk",
"Australian Outback",
"Autumn",
"Baroque",
"Bauhaus",
"Beach Day",
"Cabincore",
"City Pop",
"Classicism",
"Cottagecore",
"Cyberprep",
"Danish Pastel",
"Dark Nautical",
"Decopunk",
"Desertwave",
"Diner",
"Earthcore",
"Elizabethan England",
"Forestpunk",
"Gardencore",
"Goblincore",
"Golden Hour",
"Gothic",
"Grasscore",
"Highlandcore",
"Impressionism",
"Italian Renaissance",
"Junglecore",
"Medieval",
"Miami Metro",
"Midwest Gothic",
"Military",
"Minimalism",
"Monumentality",
"Mushroomcore",
"Naturecore",
"Nautical",
"Neoclassicism",
"Neo-Romanism",
"New England Gothic",
"Nuclear",
"Ocean Academia",
"Ocean Grunge",
"Old Hollywood",
"Paleocore",
"Pirate",
"Pre-Raphaelite",
"Retro-Futurism",
"Romanticism",
"Rusticcore",
"Sandalpunk",
"Seapunk",
"Stonecore",
"Suburban",
"Swampcore",
"Victorian",
"Vintage",
"World War II"
],
"otherworldly": [
"Abstract Tech",
"Alien",
"Artificial Nature",
"Atompunk",
"Auroracore",
"Clockpunk",
"Cyberdelic",
"Cyberpunk",
"Cyberprep",
"Dark Fantasy",
"Decopunk",
"Ethereal",
"Fairy Tale",
"Fantasy",
"Futurism",
"Gadgetpunk",
"Icepunk",
"Medieval Fantasy",
"Oceanpunk",
"Post-Apocalyptic",
"Prehistoricore",
"Retro-Futurism",
"Seapunk",
"Silkpunk",
"Spacecore",
"Steampunk",
"Surrealism",
"Transhumanism",
"Underwater",
"Utopiacore",
"Wavepunk",
"Woodpunk"
]
}

GEODYNAMICS = {
    "climate": {
        "earthly": [
            "tropical",
            "subtropical",
            "temperate",
            "taiga",
            "polar",
            "Mediterranean",
            "monsoon",
            "savanna",
            "temperate steppe",
            "highland",
            "oceanic",
            "continental",
            "humid subtropical",
            "subarctic",
            "humid continental",
            "semi-arid",
            "arid"
        ],
        "otherworldly": [
            "crystal-infused",
            "time-distorting",
            "spirit-infused",
            "dimension-shifting",
            "ethereal ghost",
            "bioluminescent",
            "singing",
            "lava-filled",
            "neon-charged",
            "gravity-reversed",
            "psychotropic",
            "stardust-swept",
            "aether-kissed",
            "dream-woven",
            "frozen in time",
            "obsidian-encrusted"
        ]
    },
    "landscapes": {
        "earthly": [
            "rolling hills",
            "steep mountains",
            "dense forests",
            "wide plains",
            "towering waterfalls",
            "deep valleys",
            "cavernous caves",
            "meandering rivers",
            "sandy beaches",
            "lush wetlands",
            "frozen glaciers",
            "volcanic ashlands",
            "rocky desert",
            "salt flats",
            "coral reefs",
            "mangrove swamps",
            "fjords",
            "gorges",
            "plateaus",
            "tundra",
            "taiga", 
            "canals"
        ],
        "otherworldly": [
            "floating",
            "flowing upwards",
            "bioluminescent flora",
            "shifting glass",
            "glowing",
            "whispering",
            "phasing in and out of reality",
            "suspended in bubbles",
            "mirrored",
            "crystal-encrusted",
            "shadow-shrouded",
            "vibrating",
            "fractal",
            "echoing with unseen voices",
            "drifting between dimensions"
        ]
    },
    "size": {
        "earthly": ["Dwarf", "Earth-like", "Vast"],
        "otherworldly": ["Limitless", "Pocket Dimension", "Expanding/Contracting", "Tiny but with Huge Inner Space", "Vast but Dense with Tiny Inner Space"]
    },
    "shape": {
        "earthly": ["Planet"],
        "otherworldly": ["Cube", "Ringworld", "Dyson Sphere", "Torus", "Flatworld", "Hyperboloid", "Living Planet", "Sentient Nebula", "Star-Whale", "Immaterial Plane", "Tesseract", "Fractal Dimension", "Dreamworld"],
    },
    "time": {
        "earthly": "linear",
        "otherworldly": ["Timeless", "Eternal Day/Night", "Fluctuating Time Speed", "Retrograde Time", "Non-linear Time", "Simultaneous Past-Present-Future"],
    },
    "physics": {
        "earthly": ["Earthly"],
        "otherworldly": ["Phasing In/Out", "Temporally Unstable", "Constructed from Ideas", "Constructed from Memories", "Constructed from Emotions"]
    },
    "life": {
        "earthly": ["Flourishing Ecosystems", "High Bio-Diversity", "Endangered Balance"],
        "otherworldly": ["Single Dominant Species", "Uniform Flora", "Life as Energy", "Life as Information"]
    }
}

