GENRES = {
"earthly": [
"1950s Suburbia",
"Abstract Tech",
"Afrofuturism",
"American Pioneers",
"American Revolution",
"Americana",
"Ancient Egypt",
"Art Deco",
"Art Nouveau",
"Atompunk",
"Australian Outback",
"Autumn",
"Baroque",
"Bauhaus",
"Beach Day",
"Cabincore",
"City Pop",
"Classicism",
"Cottagecore",
"Cyberprep",
"Danish Pastel",
"Dark Nautical",
"Decopunk",
"Desertwave",
"Diner",
"Earthcore",
"Elizabethan England",
"Forestpunk",
"Gardencore",
"Goblincore",
"Golden Hour",
"Gothic",
"Grasscore",
"Highlandcore",
"Impressionism",
"Italian Renaissance",
"Junglecore",
"Medieval",
"Miami Metro",
"Midwest Gothic",
"Military",
"Minimalism",
"Monumentality",
"Mushroomcore",
"Naturecore",
"Nautical",
"Neoclassicism",
"Neo-Romanism",
"New England Gothic",
"Nuclear",
"Ocean Academia",
"Ocean Grunge",
"Old Hollywood",
"Paleocore",
"Pirate",
"Pre-Raphaelite",
"Retro-Futurism",
"Romanticism",
"Rusticcore",
"Sandalpunk",
"Seapunk",
"Stonecore",
"Suburban",
"Swampcore",
"Victorian",
"Vintage",
"World War II"
],
"otherworldly": [
"Abstract Tech",
"Alien",
"Artificial Nature",
"Atompunk",
"Auroracore",
"Clockpunk",
"Cyberdelic",
"Cyberpunk",
"Cyberprep",
"Dark Fantasy",
"Decopunk",
"Ethereal",
"Fairy Tale",
"Fantasy",
"Futurism",
"Gadgetpunk",
"Icepunk",
"Medieval Fantasy",
"Oceanpunk",
"Post-Apocalyptic",
"Prehistoricore",
"Retro-Futurism",
"Seapunk",
"Silkpunk",
"Spacecore",
"Steampunk",
"Surrealism",
"Transhumanism",
"Underwater",
"Utopiacore",
"Wavepunk",
"Woodpunk"
]
}

GEODYNAMICS = {
    "climate": {
        "earthly": [
            "tropical rainforest",
            "subtropical desert",
            "temperate forest",
            "boreal forest (taiga)",
            "tundra",
            "polar ice cap",
            "Mediterranean",
            "monsoon",
            "savanna",
            "temperate steppe",
            "highland",
            "oceanic",
            "continental",
            "humid subtropical",
            "subarctic",
            "humid continental",
            "semi-arid",
            "arid"
        ],
        "twist": [
            "crystal-infused",
            "time-distorting",
            "spirit-infused",
            "dimension-shifting",
            "ethereal ghost",
            "bioluminescent",
            "singing",
            "lava-filled",
            "neon-charged",
            "gravity-reversed",
            "psychotropic",
            "stardust-swept",
            "aether-kissed",
            "dream-woven",
            "frozen in time",
            "obsidian-encrusted"
        ]
    },
    "landscape": {
        "earthly": [
            "rolling hills",
            "steep mountains",
            "dense forests",
            "wide plains",
            "towering waterfalls",
            "deep valleys",
            "cavernous caves",
            "meandering rivers",
            "sandy beaches",
            "lush wetlands",
            "frozen glaciers",
            "volcanic ashlands",
            "rocky desert",
            "salt flats",
            "coral reefs",
            "mangrove swamps",
            "fjords",
            "gorges",
            "plateaus",
            "canals"
        ],
        "twist": [
            "floating",
            "lava-flowing",
            "waterfalls flowing upwards",
            "bioluminescent flora",
            "shifting glass",
            "glowing",
            "whispering",
            "phasing in and out of reality",
            "suspended in bubbles",
            "mirrored",
            "crystal-encrusted",
            "shadow-shrouded",
            "vibrating",
            "fractal",
            "echoing with unseen voices",
            "drifting between dimensions"
        ]
    }
}
