# Generated by Django 4.2.3 on 2023-07-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='img',
            field=models.TextField(default='none'),
        ),
    ]
